config/routes.rb
Rails.application.routes.draw do
  resources :search_analyses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "search_analyses#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/search_analysis.rb
class SearchAnalysis < ApplicationRecord
  enum :engine, { google: 0, bing: 1, duckduckgo: 2, yahoo: 3, yandex: 4, baidu: 5 }
  enum :status, { pending_search: 0, pending_chat: 1, complete: 2, failed: 3 }
  
  validates :query, presence: true
  validates :engine, presence: true
  validates :prompt, presence: true

  after_create :run_search, :run_chat

  def run_search
    return unless self.status == "pending_search"

    search_response = SerpApiServices::SearchService.new(self).call
    
    if search_response.success?
      self.search_results = search_response.results
      self.status = "pending_chat"
    else
      self.search_results = "Failed due to error: #{search_response.error.to_s}"
      self.status = "failed"
    end
    self.save
  end

  def run_chat
    return unless self.status == "pending_chat"

    chat_response = OpenAIServices::ChatService.new(self).call
    
    if chat_response.success?
      self.chat_response = chat_response.results
      self.status = "complete"
    else
      self.chat_response = "Failed due to error: #{chat_response.error.to_s}"
      self.status = "failed"
    end
    self.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/search_analyses_controller.rb
class SearchAnalysesController < ApplicationController
  before_action :set_search_analysis, only: %i[ show destroy ]

  # GET /search_analyses or /search_analyses.json
  def index
    @search_analyses = SearchAnalysis.all
  end

  # GET /search_analyses/1 or /search_analyses/1.json
  def show
  end

  # GET /search_analyses/new
  def new
    @search_analysis = SearchAnalysis.new
  end

  # POST /search_analyses or /search_analyses.json
  def create
    @search_analysis = SearchAnalysis.new(search_analysis_params)

    respond_to do |format|
      if @search_analysis.save
        format.html { redirect_to search_analysis_url(@search_analysis), notice: "Search analysis was successfully created." }
        format.json { render :show, status: :created, location: @search_analysis }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @search_analysis.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /search_analyses/1 or /search_analyses/1.json
  def destroy
    @search_analysis.destroy

    respond_to do |format|
      format.html { redirect_to search_analyses_url, notice: "Search analysis was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search_analysis
      @search_analysis = SearchAnalysis.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def search_analysis_params
      params.require(:search_analysis).permit(:query, :engine, :prompt)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_analyses_helper.rb
module SearchAnalysesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchResultsAiAnalyzer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/search_analyses/_form.html.erb
<%= form_with(model: search_analysis, class: "contents") do |form| %>
  <% if search_analysis.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(search_analysis.errors.count, "error") %> prohibited this search_analysis from being saved:</h2>

      <ul>
        <% search_analysis.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :query, "Search Query" %>
    <%= form.text_field :query, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
      <%= form.label :engine, "Search Engine" %>
      <%= form.select(:engine, ['google', 'bing', 'duckduckgo', 'yahoo', 'yandex', 'baidu'], { :class => "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" }) %>
  </div>

  <div class="my-5">
    <%= form.label :prompt, "Chat Prompt" %>
    <%= form.text_area :prompt, rows: 3, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/search_analyses/_search_analysis.html.erb
<div id="<%= dom_id search_analysis %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Query:</strong>
    <%= search_analysis.query %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Engine:</strong>
    <%= search_analysis.engine %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Prompt:</strong>
    <%= search_analysis.prompt %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Search results:</strong>
    <%= simple_format(search_analysis.search_results) %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Chat response:</strong>
    <%= simple_format(search_analysis.chat_response) %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this search analysis", search_analysis, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/search_analyses/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Search analyses</h1>
    <%= link_to "New search analysis", new_search_analysis_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="search_analyses" class="min-w-full">
    <%= render @search_analyses %>
  </div>
</div>

app/views/search_analyses/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New search analysis</h1>

  <%= render "form", search_analysis: @search_analysis %>

  <%= link_to "Back to search analyses", search_analyses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/search_analyses/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @search_analysis %>

    <div class="inline-block ml-2">
      <%= button_to "Destroy this search_analysis", search_analysis_path(@search_analysis), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to search_analyses", search_analyses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>